export const path = {
    Batch : "Batch",
    GetAllRollNoByBatch: "RollNumber/GetAllRollNoByBatch?BatchId=",
    PostBatch : "RollNumber/PostBatch",
    Qualification:"Qualification",
    Company : "Company",
    IndustryType : "IndustryType",
    EmploymentType : "EmploymentType",
    GetByCountry : "CommonType/GetByCountry",
    GetByState : "CommonType/GetByState?CountryId=",
    GetByCity : "CommonType/GetByCity?StateId=",
    GetEvent : "Event/Get",
    PostCountry : "CommonType/PostCountry",
    PutCountry : "CommonType/PutCountry",
    DeleteCountry : "CommonType/DeleteCountry",
    PostState : "CommonType/PostState",
    PutState : "CommonType/PutState",
    DeleteState : "CommonType/DeleteState",
    PostCity : "CommonType/PostCity",
    DeleteCity : "CommonType/DeleteCity",
    PutCity : "CommonType/PutCity",
    GetUserList : "User/GetUserList",
    NewUserRegister: "User/NewUserRegister",
    UserProfessionaldetails : "User/UserProfessionalEdit/",
    InsertMemembership : "User/InsertMemembership",
    UserPersonalEdit : "User/UserPersonalEdit/",
    Account :"Account",
    Delete : "RollNumber/Delete",
    Home : "Home/GetIndexCountMethod",
    Postevent: "Event/Post",
    Deleteevent: "Event/Delete",
    Updateevents: "Event/Put",
    EventVideo: "EventVideo/Get",
    postEventVideo:"EventVideo/Post",
    GetUserListByFilter:"User/GetUserListByFilter",
    DeleteRollNumber:"RollNumber/UpdateRollNo",
    UserPutPersonalInfo : "User/PutPersonalInfo",
    PutProfessionalInfo : "User/PutProfessionalInfo",
    DeleteProfessionalInfo : "User/DeleteProfessionalInfo",
    GetManageUserByFilter : "User/GetManageUserByFilter",
    GETActive:"User/GETActive",
    GETMemberType:"User/GETMemberType",
    GETObituary:"User/GETObituary"

    

    
}